### PR TITLE
Update interface.c

### PR DESCRIPTION
**Pull request by erdies**
This is to enable 2k monitors for fullscreen. Custom resolution are rejected if they are not in the list.

### CODE REVIEW

**Comment by pjbroad** [comment]
This will be a useful change, thanks for doing it.  However, you have changed the order of the display modes which unfortunately, means that anyone with that mode enabled in their el.ini file will get the wrong mode when starting the client.  Could you change the pull request to add the new mode at the end of the list.  Also, perhaps you could add the 4k mode too 3840 x 2160.

**Comment by erdies** [comment]
Thanks for pointing to this, will do it!

**Comment by erdies** [comment]
Changes are done. I added the 4k mode, too.

**Comment by pjbroad** [comment]
Thanks.  All merged.

**Pull request merged**
